version: '3.8'

services:
  app:
    image: minha-imagem
    environment:
      - DB_USER=gympoison
      - DB_PASSWORD=123456
      - DB_NAME=ecommerce
    networks:
      - app_network

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./certs:/etc/nginx/certs
    ports:
      - "443:443"
      - "80:80"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge