version: "3"

services:
  backend:
    build:
      context: ./BackEnd
      dockerfile: Dockerfile
    command: ["./wait-for-it.sh", "db:3306", "--", "npm", "run", "dev"]
    container_name: backend
    env_file:
      - ./BackEnd/.env
    depends_on:
      - db
    networks:
      - app_network
    ports:
      - "3000:3000"

  frontend:
    build: ./FrontEnd/my-app
    container_name: frontend
    ports:
      - "8080:80"
    networks:
      - app_network

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./certs:/etc/nginx/certs
    ports:
      - "443:443"
      - "80:80"
    depends_on:
      - backend
      - frontend
    networks:
      - app_network

  db:
    image: mysql:8
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: ecommerce
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
