version: "3"

services:
  backend:
    build: ./BackEnd
    container_name: backend
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=sua_senha
      - DB_DATABASE=ecommerce
    depends_on:
      - db
    networks:
      - app_network
<<<<<<< HEAD
    restart: always
    command: ["/wait-for-it.sh", "db:3306", "--", "npm", "run", "dev"]
    extra_hosts:
      - "host.docker.internal:host-gateway"
=======
>>>>>>> 082efb170aa04a841603030106c5a6bd2f859619

  frontend:
    build: ./FrontEnd/my-app
    container_name: frontend
    ports:
<<<<<<< HEAD
      - "3000:3000"
=======
      - "8080:80"
>>>>>>> 082efb170aa04a841603030106c5a6bd2f859619
    networks:
      - app_network

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./certs:/etc/nginx/certs
    ports:
      - "443:443"
      - "80:80"
    depends_on:
      - backend
      - frontend
    networks:
      - app_network

  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: sua_senha
      MYSQL_DATABASE: ecommerce
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
